// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FloatingIPAssignmentInitParameters struct {

	// ID of the Floating IP.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/server/v1alpha1.FloatingIP
	FloatingIPID *float64 `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// Reference to a FloatingIP in server to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDRef *v1.NamespacedReference `json:"floatingIpIdRef,omitempty" tf:"-"`

	// Selector for a FloatingIP in server to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDSelector *v1.NamespacedSelector `json:"floatingIpIdSelector,omitempty" tf:"-"`

	// Server to assign the Floating IP to.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/server/v1alpha1.Server
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Reference to a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDRef *v1.NamespacedReference `json:"serverIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDSelector *v1.NamespacedSelector `json:"serverIdSelector,omitempty" tf:"-"`
}

type FloatingIPAssignmentObservation struct {

	// ID of the Floating IP.
	FloatingIPID *float64 `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// (int) Unique ID of the Floating IP Assignment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Server to assign the Floating IP to.
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`
}

type FloatingIPAssignmentParameters struct {

	// ID of the Floating IP.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/server/v1alpha1.FloatingIP
	// +kubebuilder:validation:Optional
	FloatingIPID *float64 `json:"floatingIpId,omitempty" tf:"floating_ip_id,omitempty"`

	// Reference to a FloatingIP in server to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDRef *v1.NamespacedReference `json:"floatingIpIdRef,omitempty" tf:"-"`

	// Selector for a FloatingIP in server to populate floatingIpId.
	// +kubebuilder:validation:Optional
	FloatingIPIDSelector *v1.NamespacedSelector `json:"floatingIpIdSelector,omitempty" tf:"-"`

	// Server to assign the Floating IP to.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Reference to a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDRef *v1.NamespacedReference `json:"serverIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDSelector *v1.NamespacedSelector `json:"serverIdSelector,omitempty" tf:"-"`
}

// FloatingIPAssignmentSpec defines the desired state of FloatingIPAssignment
type FloatingIPAssignmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FloatingIPAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FloatingIPAssignmentInitParameters `json:"initProvider,omitempty"`
}

// FloatingIPAssignmentStatus defines the observed state of FloatingIPAssignment.
type FloatingIPAssignmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FloatingIPAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FloatingIPAssignment is the Schema for the FloatingIPAssignments API. Provides a Hetzner Cloud Floating IP Assignment to assign a Floating IP to a Hetzner Cloud Server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,hetzner}
type FloatingIPAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              FloatingIPAssignmentSpec   `json:"spec"`
	Status            FloatingIPAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FloatingIPAssignmentList contains a list of FloatingIPAssignments
type FloatingIPAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FloatingIPAssignment `json:"items"`
}

// Repository type metadata.
var (
	FloatingIPAssignment_Kind             = "FloatingIPAssignment"
	FloatingIPAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FloatingIPAssignment_Kind}.String()
	FloatingIPAssignment_KindAPIVersion   = FloatingIPAssignment_Kind + "." + CRDGroupVersion.String()
	FloatingIPAssignment_GroupVersionKind = CRDGroupVersion.WithKind(FloatingIPAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&FloatingIPAssignment{}, &FloatingIPAssignmentList{})
}
