// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *FirewallAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FloatingIP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FloatingIPAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NetworkAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PlacementGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Server) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Snapshot) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSHKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Volume) Hub() {}
