// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AuthoritativeNameserversInitParameters struct {
}

type AuthoritativeNameserversObservation struct {

	// (List of String) Authoritative Hetzner nameservers assigned to the Zone.
	// Authoritative Hetzner nameservers assigned to the Zone.
	Assigned []*string `json:"assigned,omitempty" tf:"assigned,omitempty"`
}

type AuthoritativeNameserversParameters struct {
}

type PrimaryNameserversInitParameters struct {

	// (String) Public IPv4 or IPv6 address of the primary nameserver.
	// Public IPv4 or IPv6 address of the primary nameserver.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (Number) Port of the primary nameserver.
	// Port of the primary nameserver.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Transaction signature (TSIG) algorithm used to generate the TSIG key.
	// Transaction signature (TSIG) algorithm used to generate the TSIG key.
	TsigAlgorithm *string `json:"tsigAlgorithm,omitempty" tf:"tsig_algorithm,omitempty"`

	// (String) Transaction signature (TSIG) key
	// Transaction signature (TSIG) key
	TsigKey *string `json:"tsigKey,omitempty" tf:"tsig_key,omitempty"`
}

type PrimaryNameserversObservation struct {

	// (String) Public IPv4 or IPv6 address of the primary nameserver.
	// Public IPv4 or IPv6 address of the primary nameserver.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (Number) Port of the primary nameserver.
	// Port of the primary nameserver.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Transaction signature (TSIG) algorithm used to generate the TSIG key.
	// Transaction signature (TSIG) algorithm used to generate the TSIG key.
	TsigAlgorithm *string `json:"tsigAlgorithm,omitempty" tf:"tsig_algorithm,omitempty"`

	// (String) Transaction signature (TSIG) key
	// Transaction signature (TSIG) key
	TsigKey *string `json:"tsigKey,omitempty" tf:"tsig_key,omitempty"`
}

type PrimaryNameserversParameters struct {

	// (String) Public IPv4 or IPv6 address of the primary nameserver.
	// Public IPv4 or IPv6 address of the primary nameserver.
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// (Number) Port of the primary nameserver.
	// Port of the primary nameserver.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) Transaction signature (TSIG) algorithm used to generate the TSIG key.
	// Transaction signature (TSIG) algorithm used to generate the TSIG key.
	// +kubebuilder:validation:Optional
	TsigAlgorithm *string `json:"tsigAlgorithm,omitempty" tf:"tsig_algorithm,omitempty"`

	// (String) Transaction signature (TSIG) key
	// Transaction signature (TSIG) key
	// +kubebuilder:validation:Optional
	TsigKey *string `json:"tsigKey,omitempty" tf:"tsig_key,omitempty"`
}

type ZoneInitParameters struct {

	// (Boolean) Whether delete protection is enabled.
	// Whether delete protection is enabled.
	DeleteProtection *bool `json:"deleteProtection,omitempty" tf:"delete_protection,omitempty"`

	// defined labels (key-value pairs) for the resource.
	// User-defined [labels](https://docs.hetzner.cloud/reference/cloud#labels) (key-value pairs) for the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Mode of the Zone.
	// Mode of the Zone.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) Name of the Zone.
	// Name of the Zone.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) Primary nameservers of the Zone. Forbidden when mode is primary and required when mode is secondary. (see below for nested schema)
	PrimaryNameservers []PrimaryNameserversInitParameters `json:"primaryNameservers,omitempty" tf:"primary_nameservers,omitempty"`

	// (Number) Default Time To Live (TTL) of the Zone.
	// Default Time To Live (TTL) of the Zone.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type ZoneObservation struct {

	// (Attributes) Authoritative nameservers of the Zone. (see below for nested schema)
	AuthoritativeNameservers *AuthoritativeNameserversObservation `json:"authoritativeNameservers,omitempty" tf:"authoritative_nameservers,omitempty"`

	// (Boolean) Whether delete protection is enabled.
	// Whether delete protection is enabled.
	DeleteProtection *bool `json:"deleteProtection,omitempty" tf:"delete_protection,omitempty"`

	// (Number) ID of the Zone.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// defined labels (key-value pairs) for the resource.
	// User-defined [labels](https://docs.hetzner.cloud/reference/cloud#labels) (key-value pairs) for the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Mode of the Zone.
	// Mode of the Zone.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) Name of the Zone.
	// Name of the Zone.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) Primary nameservers of the Zone. Forbidden when mode is primary and required when mode is secondary. (see below for nested schema)
	PrimaryNameservers []PrimaryNameserversObservation `json:"primaryNameservers,omitempty" tf:"primary_nameservers,omitempty"`

	// (String) Registrar of the Zone.
	// Registrar of the Zone.
	Registrar *string `json:"registrar,omitempty" tf:"registrar,omitempty"`

	// (Number) Default Time To Live (TTL) of the Zone.
	// Default Time To Live (TTL) of the Zone.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type ZoneParameters struct {

	// (Boolean) Whether delete protection is enabled.
	// Whether delete protection is enabled.
	// +kubebuilder:validation:Optional
	DeleteProtection *bool `json:"deleteProtection,omitempty" tf:"delete_protection,omitempty"`

	// defined labels (key-value pairs) for the resource.
	// User-defined [labels](https://docs.hetzner.cloud/reference/cloud#labels) (key-value pairs) for the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Mode of the Zone.
	// Mode of the Zone.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String) Name of the Zone.
	// Name of the Zone.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes List) Primary nameservers of the Zone. Forbidden when mode is primary and required when mode is secondary. (see below for nested schema)
	// +kubebuilder:validation:Optional
	PrimaryNameservers []PrimaryNameserversParameters `json:"primaryNameservers,omitempty" tf:"primary_nameservers,omitempty"`

	// (Number) Default Time To Live (TTL) of the Zone.
	// Default Time To Live (TTL) of the Zone.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// ZoneSpec defines the desired state of Zone
type ZoneSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ZoneParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZoneInitParameters `json:"initProvider,omitempty"`
}

// ZoneStatus defines the observed state of Zone.
type ZoneStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZoneObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Zone is the Schema for the Zones API. Provides a Hetzner Cloud Zone resource. This can be used to create, modify, and delete Zones. For Internationalized domain names (IDN), see the provider::hcloud::idna function. See the Zones API documentation https://docs.hetzner.cloud/reference/cloud#zones for more details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,hetzner}
type Zone struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mode) || (has(self.initProvider) && has(self.initProvider.mode))",message="spec.forProvider.mode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZoneSpec   `json:"spec"`
	Status ZoneStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneList contains a list of Zones
type ZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Zone `json:"items"`
}

// Repository type metadata.
var (
	Zone_Kind             = "Zone"
	Zone_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Zone_Kind}.String()
	Zone_KindAPIVersion   = Zone_Kind + "." + CRDGroupVersion.String()
	Zone_GroupVersionKind = CRDGroupVersion.WithKind(Zone_Kind)
)

func init() {
	SchemeBuilder.Register(&Zone{}, &ZoneList{})
}
