// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RecordsInitParameters struct {

	// (String) Comment of the record.
	// Comment of the record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Value of the record.
	// Value of the record.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RecordsObservation struct {

	// (String) Comment of the record.
	// Comment of the record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Value of the record.
	// Value of the record.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RecordsParameters struct {

	// (String) Comment of the record.
	// Comment of the record.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Value of the record.
	// Value of the record.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ZoneRRSetInitParameters struct {

	// (Boolean) Whether change protection is enabled.
	// Whether change protection is enabled.
	ChangeProtection *bool `json:"changeProtection,omitempty" tf:"change_protection,omitempty"`

	// defined labels (key-value pairs) for the resource.
	// User-defined [labels](https://docs.hetzner.cloud/reference/cloud#labels) (key-value pairs) for the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (Attributes Set) Records of the Zone RRSet. (see below for nested schema)
	Records []RecordsInitParameters `json:"records,omitempty" tf:"records,omitempty"`

	// (Number) Time To Live (TTL) of the Zone RRSet.
	// Time To Live (TTL) of the Zone RRSet.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type ZoneRRSetObservation struct {

	// (Boolean) Whether change protection is enabled.
	// Whether change protection is enabled.
	ChangeProtection *bool `json:"changeProtection,omitempty" tf:"change_protection,omitempty"`

	// (String) ID of the Zone RRSet.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// defined labels (key-value pairs) for the resource.
	// User-defined [labels](https://docs.hetzner.cloud/reference/cloud#labels) (key-value pairs) for the resource.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the Zone RRSet.
	// Name of the Zone RRSet.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes Set) Records of the Zone RRSet. (see below for nested schema)
	Records []RecordsObservation `json:"records,omitempty" tf:"records,omitempty"`

	// (Number) Time To Live (TTL) of the Zone RRSet.
	// Time To Live (TTL) of the Zone RRSet.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) Type of the Zone RRSet.
	// Type of the Zone RRSet.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) ID or Name of the parent Zone.
	// ID or Name of the parent Zone.
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type ZoneRRSetParameters struct {

	// (Boolean) Whether change protection is enabled.
	// Whether change protection is enabled.
	// +kubebuilder:validation:Optional
	ChangeProtection *bool `json:"changeProtection,omitempty" tf:"change_protection,omitempty"`

	// defined labels (key-value pairs) for the resource.
	// User-defined [labels](https://docs.hetzner.cloud/reference/cloud#labels) (key-value pairs) for the resource.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Name of the Zone RRSet.
	// Name of the Zone RRSet.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// (Attributes Set) Records of the Zone RRSet. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Records []RecordsParameters `json:"records,omitempty" tf:"records,omitempty"`

	// (Number) Time To Live (TTL) of the Zone RRSet.
	// Time To Live (TTL) of the Zone RRSet.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// (String) Type of the Zone RRSet.
	// Type of the Zone RRSet.
	// +kubebuilder:validation:Required
	Type *string `json:"type" tf:"type,omitempty"`

	// (String) ID or Name of the parent Zone.
	// ID or Name of the parent Zone.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/cluster/dns/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	Zone *string `json:"zone,omitempty" tf:"zone,omitempty"`

	// Reference to a Zone in dns to populate zone.
	// +kubebuilder:validation:Optional
	ZoneRef *v1.Reference `json:"zoneRef,omitempty" tf:"-"`

	// Selector for a Zone in dns to populate zone.
	// +kubebuilder:validation:Optional
	ZoneSelector *v1.Selector `json:"zoneSelector,omitempty" tf:"-"`
}

// ZoneRRSetSpec defines the desired state of ZoneRRSet
type ZoneRRSetSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ZoneRRSetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZoneRRSetInitParameters `json:"initProvider,omitempty"`
}

// ZoneRRSetStatus defines the observed state of ZoneRRSet.
type ZoneRRSetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZoneRRSetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZoneRRSet is the Schema for the ZoneRRSets API. Provides a Hetzner Cloud Zone Resource Record Set (RRSet) resource. This can be used to create, modify, and delete Zone RRSets. See the Zone RRSets API documentation https://docs.hetzner.cloud/reference/cloud#zone-rrsets for more details. RRSets of type TXT: The format of TXT records must consist of one or many quoted strings of 255 characters. A helper function to format TXT record is available at provider::hcloud::txt_record. See the examples for more details.remove the RRSet from the state, instead of deleting it.set the SOA record SERIAL value to 0 before saving it to the state, as this value is automatically incremented by the API and would cause issues otherwise.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,hetzner}
type ZoneRRSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.records) || (has(self.initProvider) && has(self.initProvider.records))",message="spec.forProvider.records is a required parameter"
	Spec   ZoneRRSetSpec   `json:"spec"`
	Status ZoneRRSetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZoneRRSetList contains a list of ZoneRRSets
type ZoneRRSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZoneRRSet `json:"items"`
}

// Repository type metadata.
var (
	ZoneRRSet_Kind             = "ZoneRRSet"
	ZoneRRSet_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZoneRRSet_Kind}.String()
	ZoneRRSet_KindAPIVersion   = ZoneRRSet_Kind + "." + CRDGroupVersion.String()
	ZoneRRSet_GroupVersionKind = CRDGroupVersion.WithKind(ZoneRRSet_Kind)
)

func init() {
	SchemeBuilder.Register(&ZoneRRSet{}, &ZoneRRSetList{})
}
