apiVersion: server.hetzner.m.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: server/v1alpha1/simple-server
  labels:
    testing.upbound.io/example-name: simple-server
  name: simple-server
  namespace: crossplane-system
spec:
  forProvider:
    image: debian-12
    labels:
      app: simple-server
      environment: demo
    location: nbg1
    name: simple-server
    publicNet:
    - ipv4Enabled: true
      ipv6Enabled: true
    serverType: cx23
    userData: |
      #cloud-config
      package_update: true
      packages:
      - nginx
      write_files:
      - path: /var/www/html/index.html
        permissions: "0644"
        content: |
          provider-hetzner simple server example
      runcmd:
      - systemctl enable nginx
      - systemctl restart nginx
