// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type LoadBalancerTargetInitParameters struct {

	// use the private IP to connect to
	// Load Balancer targets. Only allowed if type is server or
	// label_selector.
	UsePrivateIP *bool `json:"usePrivateIp,omitempty" tf:"use_private_ip,omitempty"`
}

type LoadBalancerTargetObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP address for an IP Target. Required if
	// type is ip.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Label Selector selecting targets
	// for this Load Balancer. Required if type is label_selector.
	LabelSelector *string `json:"labelSelector,omitempty" tf:"label_selector,omitempty"`

	// ID of the Load Balancer to which
	// the target gets attached.
	LoadBalancerID *float64 `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// ID of the server which should be a
	// target for this Load Balancer. Required if type is server
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Type of the target. Possible values
	// server, label_selector, ip.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// use the private IP to connect to
	// Load Balancer targets. Only allowed if type is server or
	// label_selector.
	UsePrivateIP *bool `json:"usePrivateIp,omitempty" tf:"use_private_ip,omitempty"`
}

type LoadBalancerTargetParameters struct {

	// IP address for an IP Target. Required if
	// type is ip.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Label Selector selecting targets
	// for this Load Balancer. Required if type is label_selector.
	// +kubebuilder:validation:Optional
	LabelSelector *string `json:"labelSelector,omitempty" tf:"label_selector,omitempty"`

	// ID of the Load Balancer to which
	// the target gets attached.
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/loadbalancer/v1alpha1.LoadBalancer
	// +kubebuilder:validation:Optional
	LoadBalancerID *float64 `json:"loadBalancerId,omitempty" tf:"load_balancer_id,omitempty"`

	// Reference to a LoadBalancer in loadbalancer to populate loadBalancerId.
	// +kubebuilder:validation:Optional
	LoadBalancerIDRef *v1.NamespacedReference `json:"loadBalancerIdRef,omitempty" tf:"-"`

	// Selector for a LoadBalancer in loadbalancer to populate loadBalancerId.
	// +kubebuilder:validation:Optional
	LoadBalancerIDSelector *v1.NamespacedSelector `json:"loadBalancerIdSelector,omitempty" tf:"-"`

	// ID of the server which should be a
	// target for this Load Balancer. Required if type is server
	// +crossplane:generate:reference:type=github.com/miaits/provider-hetzner/apis/namespaced/server/v1alpha1.Server
	// +kubebuilder:validation:Optional
	ServerID *float64 `json:"serverId,omitempty" tf:"server_id,omitempty"`

	// Reference to a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDRef *v1.NamespacedReference `json:"serverIdRef,omitempty" tf:"-"`

	// Selector for a Server in server to populate serverId.
	// +kubebuilder:validation:Optional
	ServerIDSelector *v1.NamespacedSelector `json:"serverIdSelector,omitempty" tf:"-"`

	// Type of the target. Possible values
	// server, label_selector, ip.
	// +kubebuilder:validation:Required
	Type *string `json:"type" tf:"type,omitempty"`

	// use the private IP to connect to
	// Load Balancer targets. Only allowed if type is server or
	// label_selector.
	// +kubebuilder:validation:Optional
	UsePrivateIP *bool `json:"usePrivateIp,omitempty" tf:"use_private_ip,omitempty"`
}

// LoadBalancerTargetSpec defines the desired state of LoadBalancerTarget
type LoadBalancerTargetSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            LoadBalancerTargetParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LoadBalancerTargetInitParameters `json:"initProvider,omitempty"`
}

// LoadBalancerTargetStatus defines the observed state of LoadBalancerTarget.
type LoadBalancerTargetStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LoadBalancerTargetObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LoadBalancerTarget is the Schema for the LoadBalancerTargets API. Adds a target to a Hetzner Cloud Load Balancer.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,hetzner}
type LoadBalancerTarget struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LoadBalancerTargetSpec   `json:"spec"`
	Status            LoadBalancerTargetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LoadBalancerTargetList contains a list of LoadBalancerTargets
type LoadBalancerTargetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LoadBalancerTarget `json:"items"`
}

// Repository type metadata.
var (
	LoadBalancerTarget_Kind             = "LoadBalancerTarget"
	LoadBalancerTarget_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LoadBalancerTarget_Kind}.String()
	LoadBalancerTarget_KindAPIVersion   = LoadBalancerTarget_Kind + "." + CRDGroupVersion.String()
	LoadBalancerTarget_GroupVersionKind = CRDGroupVersion.WithKind(LoadBalancerTarget_Kind)
)

func init() {
	SchemeBuilder.Register(&LoadBalancerTarget{}, &LoadBalancerTargetList{})
}
